services:
  postgres:
    build:
      context: ./db
    container_name: "postgres-user-api"
    image: "postgres:alpine3.18"
    restart: "unless-stopped"
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  migrator:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      DB_HOST: postgres 
    build:
      dockerfile: "./migrator.Dockerfile"
    restart: "on-failure"

volumes:
  postgres_volume:
