name: "GO APP CI"
on:
  push:
    branches:
      - testing
jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63
  unit_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v4
      - name: "Set up"
        uses: "actions/setup-go@v5"
        with:
          go-version: 1.23
          cache-dependency-path: go.sum
      - name: Run unit tests
        run: go test -run 'Unit' -v ./...
  integration_tests:
    env:
      TEST_DB_DSN: "host=localhost port=55433 dbname=test user=test password=test sslmode=disable"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v4
      - name: "set up db container"
        run: |
          docker compose -f ./db/docker-compose.test.yml up -d --wait
      - name: "Set up GO"
        uses: "actions/setup-go@v5"
        with:
          go-version: 1.23
          cache-dependency-path: go.sum
      - name: "Wait for DB instance"
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 55433 && exit 0
            sleep 1
          done
          exit 1
      - name: Run integration tests
        run: TEST_DB_DSN="$TEST_DB_DSN" GRPC_TEST_ADDR="localhost:8889" go test -run 'Integration' ./... -v
  build:
    runs-on: ubuntu-22.04
    needs: [linter, unit_tests, integration_tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - name: "build"
        run: go build -o ./bin/ -v ./...
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: go-app-binary
          path: ./bin/
